### ISSUE TITLE
打开闪退

### ISSUE THREAD

**Issue by sudo0m** [LeonNOV/BiuVideo#2]
联网后登录后进入首页等推荐加载完闪退，不联网打不开闪退，安卓10 坚果pro3，已给全部权限

**Comment by sudo0m** [comment]
软件版本3.0.0 beta

**Comment by yihuayishijie43** [comment]
同闪退，版本3.0.0-beta，华为鸿蒙2.0.0

**Comment by lzw-723** [comment]
问题已经解决了(～￣▽￣)～
就等合并PR了 #3
